version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: mindmate_db
    environment:
      POSTGRES_USER: mindmate
      POSTGRES_PASSWORD: mindmate
      POSTGRES_DB: mindmatedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
